### ISSUE TITLE
打了混淆后接受不到任何信息

### ISSUE THREAD

**Issue by juenuo** [Jasonzhou613/JRxBus2#1]

**Comment by Jasonzhou613** [comment]
你好，
RxBus2库已经更新到v1.0.3版本，已解决了混淆后接收不到信息的问题。
添加以下混淆规则：
-dontoptimize
-dontusemixedcaseclassnames

-keep class com.ttsea.jrxbus2**{*;}
-keep class io.reactivex**{*;}

-keepclassmembers class * {
    public *** on*Event(***);
}

具体可看[RxBus2](https://github.com/Jasonzhou613/JRxBus2)的描述
