### ISSUE TITLE
不需要一个isRegister来判断是否已经订阅吗

### ISSUE THREAD

**Issue by TianGuisen** [Jasonzhou613/JRxBus2#2]
如果在baseActivity的onDestroy的时候不管有没有订阅都统一取消订阅会不会不妥?

**Comment by Jasonzhou613** [comment]
这个是不需要的，因为在代码里已经有判断了
`/** 注册 */
    public void register(Object subscriber) {
        //避免重复
        if (subscribersMap.containsKey(subscriber)) {
            return;
        }
      ...
  }
`
`    private void unSubscribeBySubscriber(Object subscriber) {
        List<Disposable> disposables = disposablesMap.get(subscriber);
        if (disposables != null) {
            while (disposables.size() > 0) {
                Disposable disposable = disposables.remove(0);
                if (disposable != null) {
                    disposable.dispose();
                }
            }
        }
        disposablesMap.remove(subscriber);
    }`

**Comment by Jasonzhou613** [comment]
这里是不需要加这个判断的，在注册和反注册时，都是有进行判断的：

public void register(Object subscriber) {
	//避免重复
	if (subscribersMap.containsKey(subscriber)) {
		return;
	}
	...
}

private void unSubscribeBySubscriber(Object subscriber) {
	List<Disposable> disposables = disposablesMap.get(subscriber);
	if (disposables != null) {
		while (disposables.size() > 0) {
			Disposable disposable = disposables.remove(0);
			if (disposable != null) {
				disposable.dispose();
			}
		}
	}
	disposablesMap.remove(subscriber);
}
