### ISSUE TITLE
为什么要设计成Event结尾才能收到消息呢

### ISSUE THREAD

**Issue by TianGuisen** [Jasonzhou613/JRxBus2#3]
有什么好处

**Comment by Jasonzhou613** [comment]
订阅方法是必须以“on”开头，以“Event”结尾，区分大小写，如"onLoginEvent()"，主要匹配方式为"on**Event()"
这样设计可以使程序的可读性更强。既然是事件的接收，所以以on开头，Event结尾，这样在方法很多的程序中就一目了然了

**Comment by TianGuisen** [comment]
那么是否能设计成不通过方法名就能成功匹配呢,毕竟已经有通过 @Subscribe注解去匹配了吧
假设可以只通过注解匹配就可以,那么下面:
作为一个工具库为其他使用者强制定下一个这样的规范是否是一个好的设计.毕竟可能就有人觉得后面加个Event太长了有洁癖不舒服..可能有个方法不仅仅是用来接收事件,更大的用处是当一个普通方法去调用,接收事件仅仅是其中一个调用方式,这种情形去改变方法名并不好吧.
我看了一下eventbus,虽然使用例子也是按照on...Event,但是只是推荐这种规范写法而已,并不是强制的,也没有加入校验.
@Subscribe(threadMode = ThreadMode.MAIN)  
public void onMessageEvent(MessageEvent event) {/* Do something */};
